name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme
      - name: Sphinx build
        run: |
          sphinx-build docs/source/ docs/build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4





# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v3
#       - name: Deploy to GitHub Pages
#         uses: actions/deploy-pages@v4
#         # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#         with:
#           # publish_branch: pages
#           # github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: docs/_build/html/
#           # force_orphan: true

